resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: github_token                    # <-- replace with your integration
      path: rimusz/jfrog-pipelines-docker-example # <-- replace with your repository name
      branches:
        include: ^main$
      buildOn:
        commit: true
        pullRequestCreate: false
        tagCreate: false

pipelines:
  - name: Docker_Build_Push_Test1
    configuration:
      integrations:
        - name: myArtifactory
    steps:
      - name: docker_build
        type: Bash
        configuration:
          affinityGroup: dbp_group
          inputResources:
            - name: dbp_repo
              trigger: true
        execution:
          onExecute:
            - cd ${res_dbp_repo_resourcePath}
            - echo "Building docker image"
            - docker build -t jfrog-platform.kube-lab.xyz/docker-local-dev/dbp:${run_number} .
      - name: docker_push
        type: Bash
        configuration:
          affinityGroup: dbp_group
          inputResources:
            - name: dbp_repo
        execution:
          onExecute:
            - echo "Pushing docker image"
            - docker push jfrog-platform.kube-lab.xyz/docker-local-dev/dbp:${run_number}
